### ISSUE TITLE
yarn dev 之后 在 dist文件夹中没有app.json的入口文件

### ISSUE THREAD

**Issue by pzx521521** [mtdhb/mp#4]
是我的操作方式不对?
因为不太懂Node.js

**Comment by zhuweiyou** [comment]
1. dist 目录下有产出文件吗？
1. 是否有报错？截图或发出来

**Comment by xonb86** [comment]
dist目录有产出文件
没报错，  但就是没有 app.json入口文件  只有两个文件夹 pages和static

**Comment by zhuweiyou** [comment]
参考了这个 https://github.com/Meituan-Dianping/mpvue/issues/822
问题已解决 https://github.com/mtdhb/mp/commit/c5816d93b25625ee79d379c8d73cc86b4aca50a1

使用最新代码，先删掉 yarn.lock 和 node_modules 再重新 yarn 就可以了。
